---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: docker://lpenz/omnilint:0.5.1
  tests:
    strategy:
        matrix:
          preset:
            - cppcheck
            - clang-tidy
            - install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: docker://lpenz/ghaction-cmake:0.22.0-debian-bookworm-amd64
        with:
          dependencies_debian: gkrellm libgtk2.0-dev libsystemd-dev
          preset: ${{ matrix.preset }}
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: DoozyX/clang-format-lint-action@v0.16.2
  publish-packagecloud:
    needs: [ omnilint, clang-format, tests ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - image: debian-bookworm-amd64
            distro: debian
            version: bookworm
          - image: ubuntu-jammy-amd64
            distro: ubuntu
            version: jammy
    steps:
      - uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v2.2.0
      - uses: docker://lpenz/ghaction-cmake:0.22.0-debian-bookworm-amd64
        if: matrix.variant.image == 'debian-bookworm-amd64'
        with:
          preset: cpack
          dependencies_debian: gkrellm libgtk2.0-dev libsystemd-dev
      - uses: docker://lpenz/ghaction-cmake:0.22.0-ubuntu-jammy-amd64
        if: matrix.variant.image == 'ubuntu-jammy-amd64'
        with:
          preset: cpack
          dependencies_debian: gkrellm libgtk2.0-dev libsystemd-dev
      - run: |
          for f in *.deb; do ls -l "$f"; dpkg --info "$f"; done
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.13.2
      - uses: docker://lpenz/ghaction-packagecloud:0.4
        if: steps.version.outputs.version_commit != ''
        with:
          repository: ${{ matrix.variant.distro }}/${{ matrix.variant.distro }}/${{ matrix.variant.version }}
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

